#define FOR_MULTIPLAYER_MACRO 0
#define OWL_DEV_MODE_MACRO 1


#define WARLORD_DATA_IS_NULL(DATA_ARRAY) (count DATA_ARRAY == 0)

#define GET_WARLORD_OWNER_ID(DATA_ARRAY) (DATA_ARRAY select 0)
#define GET_WARLORD_PLAYER(DATA_ARRAY) (DATA_ARRAY select 1)
#define GET_WARLORD_SIDE(DATA_ARRAY) (DATA_ARRAY select 2)
#define GET_WARLORD_FUNDS(DATA_ARRAY) (DATA_ARRAY select 3)

#define SET_WARLORD_OWNER_ID(DATA_ARRAY,NEW_VALUE) (DATA_ARRAY set [0,NEW_VALUE])
#define SET_WARLORD_PLAYER(DATA_ARRAY,NEW_VALUE) (DATA_ARRAY set [1,NEW_VALUE])
#define SET_WARLORD_SIDE(DATA_ARRAY,NEW_VALUE) (DATA_ARRAY set [2,NEW_VALUE])
#define SET_WARLORD_FUNDS(DATA_ARRAY,NEW_VALUE) (DATA_ARRAY set [3,NEW_VALUE])
